points:
  key:
    padding: cy
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: =row_net
        params:
          keycaps: true
          reverse: true
          hotswap: true
      choc:
        type: choc
        anchor:
          rotate: 180
        nets:
          from: =column_net
          to: =row_net
        params:
          keycaps: true
          reverse: true
  zones:
    matrix:
      anchor:
        rotate: 16
        shift: [50, -100]
      columns:
        pinky:
          row_overrides:
            bottom:
              column_net: Col4
              row_net: Row2
            home:
              column_net: Col4
              row_net: Row1
            top:
              column_net: Col4
              row_net: Row0
        ring:
          spread: 20
          rotate: -5
          origin: [-12, -19]
          stagger: 15
          row_overrides:
            bottom:
              column_net: Col3
              row_net: Row2
            home:
              column_net: Col3
              row_net: Row1
            top:
              column_net: Col3
              row_net: Row0
        middle:
          rotate: -3
          origin: [-12, -19]
          stagger: 10
          row_overrides:
            bottom:
              column_net: Col2
              row_net: Row2
            home:
              column_net: Col2
              row_net: Row1
            top:
              column_net: Col2
              row_net: Row0
        index:
          rotate: -6
          stagger: -12
          spread: 18.9
          row_overrides:
            bottom:
              column_net: Col1
              row_net: Row2
            home:
              column_net: Col1
              row_net: Row1
            top:
              column_net: Col1
              row_net: Row0
        inner:
          row_overrides:
            bottom:
              column_net: Col0
              row_net: Row2
            home:
              column_net: Col0
              row_net: Row1
            top:
              column_net: Col0
              row_net: Row0
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
          row_overrides:
            thumb:
              column_net: Col5
              row_net: Row2
        home:
          spread: 19
          rotate: -28
          origin: [-9, -9]
          row_overrides:
            thumb:
              column_net: Col5
              row_net: Row1
        far:
          spread: 19
          rotate: -28
          origin: [-9.5, -9]
          row_overrides:
            thumb:
              column_net: Col5
              row_net: Row0
      rows:
        thumb:
  rotate: -2
pcbs:
  main:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro_pretty
        anchor:
          ref: matrix_inner_home
          shift: [20, 7.75]
          rotate: -90
        params:
          orientation: down
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: matrix_inner_home
          shift: [20, -28]
          rotate: 90
        params:
          reverse: true
      via2:
        type: via
        anchor:
          ref: matrix_inner_home
          shift: [23, -28]
        nets:
          net: GND
      via3:
        type: via
        anchor:
          ref: matrix_inner_home
          shift: [17, -28]
        nets:
          net: RST
      pcm12:
        type: pcm12
        anchor:
          ref: thumbfan_near_thumb
          shift: [35.7, 6]
          rotate: 90
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      trrs:
        type: trrs
        anchor:
          ref: thumbfan_near_thumb
          shift: [38, 12]
          rotate: -90
        nets:
          A: SCL
          B: SCL
          C: GND
          D: VCC
        params:
          reverse: true
          symmetric: true
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: thumbfan_near_thumb
          shift: [20, 10]
          rotate: 90
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1.4cx , 1.3cx]
      - type: rectangle
        size: [22, 65.7]
        anchor:
          ref: matrix_inner_bottom
          shift: [9, -20]
      - type: rectangle
        size: [20, 20]
        anchor:
          ref: matrix_inner_home
          shift: [0, -40]
      - type: rectangle
        size: [20, 20]
        anchor:
          ref: matrix_inner_home
          shift: [10, -38.6]
          rotate: -56
      - type: rectangle
        size: [60, 30]
        anchor:
          ref: thumbfan_near_thumb
          shift: [-63, -11.7]
    cutout:
      - type: outline
        name: raw
        fillet: 2
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false