points:
  key:
    padding: cy
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
          hotswap: true
      choc:
        type: choc
        anchor:
          rotate: 180
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
      
  zones:
    matrix:
      anchor:
        rotate: 16
        shift: [50, -100]
      columns:
        pinky:
          row_overrides:
            bottom:
              column_net: K14
              bind: [0, 1, 0, 1]
            home:
              column_net: K13
              bind: [0, 7, 0, 1]
            top:
              column_net: K12
              bind: [0, 7, 0, 1]
        ring:
          spread: 20
          rotate: -5
          origin: [-12, -19]
          stagger: 15
          row_overrides:
            bottom:
              column_net: K11
              bind: [0, 1, 0, 7]
            home:
              column_net: K10
            top:
              column_net: K9
              bind: [0, 7, 0, 1]
        middle:
          rotate: -3
          origin: [-12, -19]
          stagger: 10
          row_overrides:
            bottom:
              column_net: K8
              bind: [0, 7, 0, 7]
            home:
              column_net: K7
              bind: [0, 0, 0, 7]
            top:
              column_net: K6
              bind: [0, 1, 0, 1]
        index:
          rotate: -6
          stagger: -12
          spread: 18.9
          row_overrides:
            bottom:
              column_net: K5
              bind: [0, 7, 0, 1]
            home:
              column_net: K4
              bind: [0, 7, 0, 7]
            top:
              column_net: K3
              bind: [0, 7, 0, 7]
        inner:
          row_overrides:
            bottom:
              column_net: K2
            home:
              column_net: K1
            top:
              column_net: K0
      rows:
        bottom:
        home:
        top:
          bind: [0, 7, 0, 0]
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
          row_overrides:
            thumb:
              column_net: K17
              bind: [20, 7, 0, 60]
        home:
          spread: 19
          rotate: -28
          origin: [-9, -9]
          row_overrides:
            thumb:
              column_net: K16
              bind: [0, 2, 0, 2]
        far:
          spread: 19
          rotate: -28
          origin: [-9.5, -9]
          row_overrides:
            thumb:
              column_net: K15
              bind: [0, 1, 0, 12]
      rows:
        thumb:
  rotate: -2
pcbs:
  main:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro_pretty_gnd
        anchor:
          ref: matrix_inner_home
          shift: [19, 9]
          rotate: -90
        params:
          orientation: down
      resetw:
        type: resetw
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: matrix_inner_home
          shift: [20, -28]
          rotate: 90
      # b3u1000p:
      #   type: b3u1000p
      #   nets:
      #     r1: RST  
      #     r2: GND
      #   anchor:
      #     ref: matrix_inner_home
      #     shift: [20, -28]
      #     rotate: 90
      #   params:
      #     reverse: true
      # via2:
      #   type: via
      #   anchor:
      #     ref: matrix_inner_home
      #     shift: [23, -28]
      #   nets:
      #     net: RST
      # via3:
      #   type: via
      #   anchor:
      #     ref: matrix_inner_home
      #     shift: [17, -28]
      #   nets:
      #     net: GND
      via4:
        type: via
        anchor:
          ref: matrix_inner_home
          shift: [24.4, -30]
        nets:
          net: RAW
      via5:
        type: via
        anchor:
          ref: matrix_inner_home
          shift: [25.5, -30]
        nets:
          net: pos
      # viar0:
      #   type: via
      #   anchor:
      #     ref: matrix_inner_top
      #     shift: [10, -0.35]
      #   nets:
      #     net: Row0
      pcm12:
        type: pcm12
        anchor:
          ref: thumbfan_near_thumb
          shift: [35.7, 6]
          rotate: 90
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      # trrs:
      #   type: trrs
      #   anchor:
      #     ref: thumbfan_near_thumb
      #     shift: [38, 12]
      #     rotate: -90
      #   nets:
      #     A: SCL
      #     B: SCL
      #     C: GND
      #     D: VCC
      #   params:
      #     reverse: true
      #     symmetric: true
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: thumbfan_near_thumb
          shift: [20, 10]
          rotate: 90
      # diode:
      #   type: diode
      #   nets:
      #     from: D1
      #     to: Row0
      #   anchor:
      #     ref: matrix_pinky_top
      #     shift: [8, -2]
      #     rotate: -90
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx - 0.5 , 1cx -0.5]
      - type: rectangle
        size: [23, 67.75]
        anchor:
          ref: matrix_inner_bottom
          shift: [8, -25]
    plate: 
      - type: keys
        side: left
        size: [1cx + 5, 1cx + 5]
      - type: rectangle
        size: [23 + 2.75, 67.75 + 2.75]
        anchor:
          ref: matrix_inner_bottom
          shift: [8, -25]
    key_zones:
      - type: rectangle # Index col
        size: [(1cx - 0.5) * 2 + 1.5, (1cy - 0.5) * 3]
        anchor:
          ref: matrix_inner_bottom
          shift: [-(1cx - 0.5) * 1.5 - 1.5, -(1cy - 0.5) * 0.5]
      - type: rectangle # middle col
        size: [(1cx - 0.5) * 2 + 1.5, (1cy - 0.5) * 3]
        anchor:
          ref: matrix_middle_bottom
          shift: [-(1cx - 0.5) * 1.5 - 1.5, -(1cy - 0.5) * 0.5]
      
    cutout:
      - type: outline
        name: raw
        fillet: 2
    cutoutbig:
      - type: outline
        name: plate
        fillet: 2
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false
    key_cutout:
      - type: outline
        name: keycap_outlines
        fillet: 1
      - type: outline
        name: key_zones
        fillet: 1 
cases:
  both_case:
    - type: outline # default option
      name: cutoutbig
      extrude: 8.6 # default = 1
      shift: [0, 0, 0] # default = [0, 0, 0]
      rotate: [0, 0, 0] # default = [0, 0, 0]
      operation: add # default = add
    - type: outline # default option
      name: cutout
      extrude: 1.6 # default = 1
      shift: [0, 0, 0] # default = [0, 0, 0]
      rotate: [0, 0, 0] # default = [0, 0, 0]
      operation: subtract # default = add
    - type: outline # default option
      name: key_cutout
      extrude: 8 # default = 1
      shift: [0, 0, 1.6] # default = [0, 0, 0]
      rotate: [0, 0, 0] # default = [0, 0, 0]
      operation: subtract # default = add
  # top_case:
  #   - type: outline # default option
  #     name: cutoutbig
  #     extrude: 9.6 # default = 1
  #     shift: [0, 0, 0] # default = [0, 0, 0]
  #     rotate: [0, 0, 0] # default = [0, 0, 0]
  #     operation: add # default = add
  #   - type: outline # default option
  #     name: cutout
  #     extrude: 1.6 # default = 1
  #     shift: [0, 0, 0] # default = [0, 0, 0]
  #     rotate: [0, 0, 0] # default = [0, 0, 0]
  #     operation: subtract # default = add
  #   - type: outline # default option
  #     name: keycap_outlines
  #     extrude: 8 # default = 1
  #     shift: [0, 0, 1.6] # default = [0, 0, 0]
  #     rotate: [0, 0, 0] # default = [0, 0, 0]
  #     operation: subtract # default = add
  # bottom_case:
  #   - type: outline # default option
  #     name: cutoutbig
  #     extrude: 10 # default = 1
  #     shift: [0, 0, 2] # default = [0, 0, 0]
  #     rotate: [0, 0, 0] # default = [0, 0, 0]
  #     operation: subtract # default = add
  #   # - type: outline # default option
  #   #   name: cutout
  #   #   extrude: 4 # default = 1
  #   #   shift: [0, 0, 2] # default = [0, 0, 0]
  #   #   rotate: [0, 0, 0] # default = [0, 0, 0]
  #   #   operation: subtract # default = add